Blast\Bundle\TestsBundle\Entity\TstFinal:
    type: entity
    table: test_final_table
    repositoryClass: Blast\Bundle\TestsBundle\Repository\TstFinalRepository
    
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type:     string(255)
            nullable: true
        code:
            type:     string(15)
            nullable: true

    oneToMany:
        final_children:
            targetEntity: Blast\Bundle\TestsBundle\Entity\TstFinal
            mappedBy: final_parent
            cascade: [persist, remove]

    manyToOne:
        final_parent:
            targetEntity: Blast\Bundle\TestsBundle\Entity\TstFinal
            inversedBy: final_children
        parent:
            targetEntity: Blast\Bundle\TestsBundle\Entity\TstParent
            inversedBy: final
            joinColumn:
                name: parent_id
                onDelete : 'CASCADE'
            cascade: [ persist, remove ]

    uniqueConstraints:
        test_finale_name_idx:
            columns: [ name ]

