Blast\Bundle\TestsBundle\Entity\TstSimple:
    type: entity
    table: test_simple_table
    repositoryClass: Blast\Bundle\TestsBundle\Repository\TstSimpleRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type:     string(255)
            nullable: true
        code:
            type:     string(15)
            nullable: true
    oneToMany:
        second:
            targetEntity: Blast\Bundle\TestsBundle\Entity\TstSecond
            mappedBy: simple
            cascade: [ remove ]

    uniqueConstraints:
        test_simple_name_idx:
            columns: [ name ]

