Blast\Bundle\TestsBundle\Entity\TstSecond:
    type: entity
    table: test_second_table
    repositoryClass: Blast\Bundle\TestsBundle\Repository\TstSecondRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:                
        name:
            type:     string(255)
            nullable: true
        code:
            type:     string(15)
            nullable: true
    manyToOne:
        simple:
            targetEntity: Blast\Bundle\TestsBundle\Entity\TstSimple
            inversedBy: second
            joinColumn:
                name: simple_id
                onDelete : 'CASCADE'
            cascade: [ remove ]

    oneToMany:
        parent:
            targetEntity: Blast\Bundle\TestsBundle\Entity\TstParent
            mappedBy: second
            cascade: [ remove ]

    uniqueConstraints:
        test_second_name_idx:
            columns: [ name ]

